### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NoahGorny** [vigo/apm-bash-completion#2]
Hello @vigo !
We use your bash completion script in our [project](https://github.com/Bash-it/bash-it) and really enjoy it :smile:

However, it seems like currently your project has no license, which will cause us to remove your script from our repo (we want to add a license and as such cannot include unlicensed work, see https://github.com/Bash-it/bash-it/issues/512) 

Could you please add a license? This will greatly help us :smiley:

**Comment by vigo** [comment]
yeah sure do. MIT ok?

**Comment by NoahGorny** [comment]
MIT would be great, thanks a lot!

**Comment by vigo** [comment]
done!
